import { LordsDay } from '../types';

export const lordsDay3: LordsDay = {
  id: 3,
  title: "Lord's Day 3",
  questions: [
    {
      id: 6,
      question: "Did God, then, create man so wicked and perverse?",
      answer: "No, on the contrary, God created man good and in his image, that is, in true righteousness and holiness, so that he might rightly know God his Creator, heartily love him, and live with him in eternal blessedness to praise and glorify him.",
    },
    {
      id: 7,
      question: "From where, then, did man's depraved nature come?",
      answer: "From the fall and disobedience of our first parents, Adam and Eve, in Paradise, for there our nature became so corrupt that we are all conceived and born in sin.",
    },
    {
      id: 8,
      question: "But are we so corrupt that we are totally unable to do any good and inclined to all evil?",
      answer: "Yes, unless we are regenerated by the Spirit of God.",
    }
  ]
};