// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npdljxzrbaatmnyvsigg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wZGxqeHpyYmFhdG1ueXZzaWdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3NzYwNDgsImV4cCI6MjA1NDM1MjA0OH0.2w4wLrP0WpVafIuQ528nKvskq-TEFatGe1_2Olnz3EI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);