export interface Question {
  id: number;
  question: string;
  answer: string;
}

export interface LordsDay {
  id: number;
  title: string;
  questions: Question[];
}

export const catechism: LordsDay[] = [
  {
    id: 1,
    title: "Lord's Day 1",
    questions: [
      {
        id: 1,
        question: "What is your only comfort in life and death?",
        answer: "That I am not my own, but belong with body and soul, both in life and in death, to my faithful Savior Jesus Christ. He has fully paid for all my sins with his precious blood and has set me free from all the power of the devil. He also preserves me in such a way that without the will of my heavenly Father not a hair can fall from my head; indeed, all things must work together for my salvation. Therefore, by his Holy Spirit he also assures me of eternal life and makes me heartily willing and ready from now on to live for him.",
      },
      {
        id: 2,
        question: "What do you need to know in order to live and die in the joy of this comfort?",
        answer: "First, how great my sins and misery are; Second, how I am delivered from all my sins and misery; Third, how I am to be thankful to God for such deliverance.",
      },
    ],
  },
  {
    id: 2,
    title: "Lord's Day 2",
    questions: [
      {
        id: 3,
        question: "From where do you know your sins and misery?",
        answer: "From the law of God.",
      },
      {
        id: 4,
        question: "What does God's law require of us?",
        answer: "Christ teaches us this in a summary in Matthew 22: Love the Lord your God with all your heart and with all your soul and with all your mind. This is the first and greatest commandment. And the second is like it: Love your neighbor as yourself. All the Law and the Prophets hang on these two commandments.",
      },
      {
        id: 5,
        question: "Can you keep all this perfectly?",
        answer: "No, I am inclined by nature to hate God and my neighbor.",
      },
    ],
  },
  {
    id: 3,
    title: "Lord's Day 3",
    questions: [
      {
        id: 6,
        question: "Did God, then, create man so wicked and perverse?",
        answer: "No, on the contrary, God created man good and in his image, that is, in true righteousness and holiness, so that he might rightly know God his Creator, heartily love him, and live with him in eternal blessedness to praise and glorify him.",
      },
      {
        id: 7,
        question: "From where, then, did man's depraved nature come?",
        answer: "From the fall and disobedience of our first parents, Adam and Eve, in Paradise, for there our nature became so corrupt that we are all conceived and born in sin.",
      },
      {
        id: 8,
        question: "But are we so corrupt that we are totally unable to do any good and inclined to all evil?",
        answer: "Yes, unless we are regenerated by the Spirit of God.",
      },
    ],
  },
  {
    id: 4,
    title: "Lord's Day 4",
    questions: [
      {
        id: 9,
        question: "But does not God do man an injustice by requiring in his law what man cannot do?",
        answer: "No, for God so created man that he was able to do it. But man, at the instigation of the devil, in deliberate disobedience, robbed himself and all his descendants of these gifts.",
      },
      {
        id: 10,
        question: "Will God allow such disobedience and apostasy to go unpunished?",
        answer: "Certainly not. He is terribly displeased with our original sin as well as our actual sins. Therefore, he will punish them by a just judgment both now and eternally, as he has declared: \"Cursed is everyone who does not continue to do everything written in the Book of the Law.\"",
      },
      {
        id: 11,
        question: "But is God not also merciful?",
        answer: "God is indeed merciful, but he is also just. His justice requires that sin committed against the most high majesty of God also be punished with the most severe, that is, with everlasting, punishment of body and soul.",
      },
    ],
  },
  {
    id: 5,
    title: "Lord's Day 5",
    questions: [
      {
        id: 12,
        question: "Since, according to God's righteous judgment, we deserve temporal and eternal punishment, how can we escape this punishment and be again received into favor?",
        answer: "God demands that his justice be satisfied. Therefore, we must make full payment, either by ourselves or through another.",
      },
      {
        id: 13,
        question: "Can we by ourselves make this payment?",
        answer: "Certainly not. On the contrary, we daily increase our debt.",
      },
      {
        id: 14,
        question: "Can any mere creature pay for us?",
        answer: "No. In the first place, God will not punish another creature for the sin which man has committed. Furthermore, no mere creature can sustain the burden of God's eternal wrath against sin and deliver others from it.",
      },
      {
        id: 15,
        question: "What kind of mediator and deliverer must we seek?",
        answer: "One who is a true and righteous man, and yet more powerful than all creatures; that is, one who is at the same time true God.",
      },
    ],
  },
  {
    id: 6,
    title: "Lord's Day 6",
    questions: [
      {
        id: 16,
        question: "Why must he be a true and righteous man?",
        answer: "He must be a true man because the justice of God requires that the same human nature which has sinned should pay for sin. He must be a righteous man because one who himself is a sinner cannot pay for others.",
      },
      {
        id: 17,
        question: "Why must he at the same time be true God?",
        answer: "He must be true God so that by the power of his divine nature he might bear in his human nature the burden of God's wrath and might obtain for us and restore to us righteousness and life.",
      },
      {
        id: 18,
        question: "But who is that Mediator who at the same time is true God and a true and righteous man?",
        answer: "Our Lord Jesus Christ, who has become for us wisdom from God – that is, our righteousness, holiness, and redemption.",
      },
      {
        id: 19,
        question: "From where do you know this?",
        answer: "From the holy gospel, which God himself first revealed in Paradise. Later, he had it proclaimed by the patriarchs and prophets, and foreshadowed by the sacrifices and other ceremonies of the law. Finally, he had it fulfilled through his only Son.",
      },
    ],
  },
  {
    id: 7,
    title: "Lord's Day 7",
    questions: [
      {
        id: 20,
        question: "Are all men, then, saved by Christ just as they perished through Adam?",
        answer: "No. Only those are saved who by a true faith are grafted into Christ and accept all his benefits.",
      },
      {
        id: 21,
        question: "What is true faith?",
        answer: "True faith is a sure knowledge whereby I accept as true all that God has revealed to us in his Word. At the same time, it is a firm confidence that not only to others, but also to me, God has granted forgiveness of sins, everlasting righteousness, and salvation, out of mere grace, only for the sake of Christ's merits.",
      },
      {
        id: 22,
        question: "What, then, must a Christian believe?",
        answer: "All that is promised us in the gospel, which the articles of our catholic and undoubted Christian faith teach us in a summary.",
      },
      {
        id: 23,
        question: "What are these articles?",
        answer: "I believe in God the Father almighty, Creator of heaven and earth… (Apostles' Creed follows).",
      },
    ],
  },
  {
    id: 8,
    title: "Lord's Day 8",
    questions: [
      {
        id: 24,
        question: "How are these articles divided?",
        answer: "Into three parts: The first is about God the Father and our creation; The second about God the Son and our redemption; The third about God the Holy Spirit and our sanctification.",
      },
      {
        id: 25,
        question: "Since there is only one God, why do you speak of three persons: Father, Son, and Holy Spirit?",
        answer: "Because God has so revealed himself in his Word that these three distinct persons are the one, true, eternal God.",
      },
    ],
  },
  {
    id: 9,
    title: "Lord's Day 9",
    questions: [
      {
        id: 26,
        question: "What do you believe when you say: I believe in God the Father almighty, Creator of heaven and earth?",
        answer: "That the eternal Father of our Lord Jesus Christ, who out of nothing created heaven and earth and all that is in them, and who still upholds and governs them by his eternal counsel and providence, is, for the sake of Christ his Son, my God and my Father. In him I trust so completely as to have no doubt that he will provide me with all things necessary for body and soul, and will also turn to my good whatever adversity he sends me in this life of sorrow. He is able to do so as almighty God, and willing also as a faithful Father.",
      },
    ],
  },
  {
    id: 10,
    title: "Lord's Day 10",
    questions: [
      {
        id: 27,
        question: "What do you understand by the providence of God?",
        answer: "God's providence is his almighty and ever-present power, whereby, as with his hand, he still upholds heaven and earth and all creatures, and so governs them that leaf and blade, rain and drought, fruitful and barren years, food and drink, health and sickness, riches and poverty, indeed, all things, come to us not by chance but by his fatherly hand.",
      },
      {
        id: 28,
        question: "What does it benefit us to know that God has created all things and still upholds them by his providence?",
        answer: "We can be patient in adversity, thankful in prosperity, and with a view to the future we can have a firm confidence in our faithful God and Father that no creature shall separate us from his love; for all creatures are so completely in his hand that without his will they cannot so much as move.",
      },
    ],
  },
  {
    id: 11,
    title: "Lord's Day 11",
    questions: [
      {
        id: 29,
        question: "Why is the Son of God called Jesus, that is, Saviour?",
        answer: "Because he saves us from all our sins, and because salvation is not to be sought or found in anyone else.",
      },
      {
        id: 30,
        question: "Do those who seek their salvation or well-being in saints, in themselves, or anywhere else, also believe in the only Saviour Jesus?",
        answer: "No. Though they boast of him in words, they in fact deny the only Saviour Jesus. For one of two things must be true: either Jesus is not a complete Saviour, or those who by true faith accept this Saviour must find in him all that is necessary for their salvation.",
      },
    ],
  },
  {
    id: 12,
    title: "Lord's Day 12",
    questions: [
      {
        id: 31,
        question: "Why is he called Christ, that is, Anointed?",
        answer: "Because he has been ordained by God the Father, and anointed with the Holy Spirit, to be our chief Prophet and Teacher, who has fully revealed to us the secret counsel and will of God concerning our redemption; our only High Priest, who by the one sacrifice of his body has redeemed us, and who continually intercedes for us before the Father; and our eternal King, who governs us by his Word and Spirit, and who defends and preserves us in the redemption obtained for us.",
      },
      {
        id: 32,
        question: "Why are you called a Christian?",
        answer: "Because I am a member of Christ by faith and thus share in his anointing, so that I may as prophet confess his name, as priest present myself a living sacrifice of thankfulness to him, and as king fight with a free and good conscience against sin and the devil in this life, and hereafter reign with him eternally over all creatures.",
      },
    ],
  },
  {
    id: 13,
    title: "Lord's Day 13",
    questions: [
      {
        id: 33,
        question: "Why is he called God's only-begotten Son, since we also are children of God?",
        answer: "Because Christ alone is the eternal, natural Son of God. We, however, are children of God by adoption, through grace, for Christ's sake.",
      },
      {
        id: 34,
        question: "Why do you call him our Lord?",
        answer: "Because he has ransomed us, body and soul, from all our sins, not with silver or gold but with his precious blood, and has freed us from all the power of the devil to make us his own possession.",
      },
    ],
  },
  {
    id: 14,
    title: "Lord's Day 14",
    questions: [
      {
        id: 35,
        question: "What do you confess when you say: He was conceived by the Holy Spirit, born of the virgin Mary?",
        answer: "The eternal Son of God, who is and remains true and eternal God, took upon himself true human nature from the flesh and blood of the virgin Mary, through the working of the Holy Spirit. Thus he is also the true seed of David, and like his brothers in every respect, yet without sin.",
      },
      {
        id: 36,
        question: "What benefit do you receive from the holy conception and birth of Christ?",
        answer: "He is our Mediator, and with his innocence and perfect holiness covers, in the sight of God, my sin, in which I was conceived and born.",
      },
    ],
  },
  {
    id: 15,
    title: "Lord's Day 15",
    questions: [
      {
        id: 37,
        question: "What do you confess when you say that he suffered?",
        answer: "During all the time he lived on earth, but especially at the end, Christ bore in body and soul the wrath of God against the sin of the whole human race. Thus, by his suffering, as the only atoning sacrifice, he has redeemed our body and soul from everlasting damnation, and obtained for us the grace of God, righteousness, and eternal life.",
      },
      {
        id: 38,
        question: "Why did he suffer under Pontius Pilate as judge?",
        answer: "Though innocent, Christ was condemned by an earthly judge, and so he freed us from the severe judgment of God that was to fall on us.",
      },
      {
        id: 39,
        question: "Does it have a special meaning that Christ was crucified and did not die in a different way?",
        answer: "Yes. Thereby I am assured that he took upon himself the curse which lay on me, for a crucified one was cursed by God.",
      },
    ],
  },
  {
    id: 16,
    title: "Lord's Day 16",
    questions: [
      {
        id: 40,
        question: "Why was it necessary for Christ to humble himself even unto death?",
        answer: "Because of the justice and truth of God satisfaction for our sins could be made in no other way than by the death of the Son of God.",
      },
      {
        id: 41,
        question: "Why was he buried?",
        answer: "His burial testified that he had really died.",
      },
      {
        id: 42,
        question: "Since Christ has died for us, why do we still have to die?",
        answer: "Our death is not a payment for our sins, but it puts an end to sin and is an entrance into eternal life.",
      },
    ],
  },
  {
    id: 17,
    title: "Lord's Day 17",
    questions: [
      {
        id: 45,
        question: "How does Christ's resurrection benefit us?",
        answer: "First, by his resurrection he has overcome death, so that he could make us share in the righteousness which he had obtained for us by his death. Second, by his power we too are raised up to a new life. Third, Christ's resurrection is to us a sure pledge of our glorious resurrection.",
      },
    ],
  },
  {
    id: 18,
    title: "Lord's Day 18",
    questions: [
      {
        id: 46,
        question: "What do you confess when you say, he ascended into heaven?",
        answer: "That Christ, before the eyes of his disciples, was taken up from the earth into heaven, and that he is there for our benefit until he comes again to judge the living and the dead.",
      },
    ],
  },
  {
    id: 19,
    title: "Lord's Day 19",
    questions: [
      {
        id: 50,
        question: "Why is it added, and sits at the right hand of God?",
        answer: "Christ ascended into heaven to manifest himself there as Head of his church, through whom the Father governs all things.",
      },
    ],
  },
  {
    id: 20,
    title: "Lord's Day 20",
    questions: [
      {
        id: 53,
        question: "What do you believe concerning the Holy Spirit?",
        answer: "First, he is, together with the Father and the Son, true and eternal God. Second, he is also given to me, to make me by true faith share in Christ and all his benefits, to comfort me, and to remain with me forever.",
      },
    ],
  },
];
